# Generated by Django 3.2.8 on 2021-11-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_committee_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
