# Generated by Django 3.2.8 on 2021-11-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image',
        ),
    ]
