# Generated by Django 3.2.8 on 2021-11-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_img_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee_list',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.committee_list'),
        ),
    ]
