# Generated by Django 3.2.8 on 2021-11-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20211103_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.committee_list'),
        ),
        migrations.AlterField(
            model_name='team',
            name='session',
            field=models.CharField(max_length=122),
        ),
    ]
