# Generated by Django 3.2.8 on 2021-11-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20211103_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
