# Generated by Django 3.2.8 on 2021-11-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_committee_list_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee_list',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
