# Generated by Django 3.2.8 on 2021-11-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0002_auto_20211104_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=122),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='last_donate',
            field=models.DateField(),
        ),
    ]
