# Generated by Django 3.2.8 on 2021-11-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_auto_20211104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='last_donate',
            field=models.DateField(),
        ),
    ]
