# Generated by Django 3.2.8 on 2021-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0011_alter_blood_donor_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor',
            name='last_donate',
            field=models.DateField(blank=True),
        ),
    ]
