# Generated by Django 3.2.8 on 2021-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0012_alter_blood_donor_last_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor',
            name='last_donate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
